---
- name: import check tasks
  block:
    - import_tasks: check_os.yml
    - import_tasks: centos_prerequisites.yml
  tags:
    - always

- import_tasks: netam_init.yml
  tags:
    - always

- name: perform installation
  block:
    - import_tasks: node_install.yml
    - import_tasks: yarn_install.yml
    - import_tasks: netam_pre.yml
    - import_tasks: netam_install.yml
  tags:
    - install

- import_tasks: netam_post.yml
  tags:
    - always

- import_tasks: db_migrate.yml
  tags:
    - install
